### ISSUE TITLE
Graph update

### ISSUE THREAD

**Issue by StijnCaerts** [StijnCaerts/Kringenzuip#1]
Make the graph update itself when a score is modified.

**Comment by katms** [comment]
I'd like to do this one.

**Comment by StijnCaerts** [comment]
Ok, great! Feel free to contact me if you have any questions.

**Comment by katms** [comment]
Should I include updating the graph when a group is added, or just for when the score changes?

EDIT: Nevermind, I figured out how to see the updated graph.
